# Generated by Django 4.1 on 2024-04-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="vendor_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
