# Generated by Django 4.1 on 2024-04-29 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_vendor_vendor_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendor",
            name="vendor_code",
        ),
    ]
