# Generated by Django 5.0.4 on 2024-05-02 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_purchaseorder_po_number'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='purchaseorder',
            table='purchase_order',
        ),
    ]
