# Generated by Django 5.0.4 on 2024-05-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_purchaseorder_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='delivery_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Expected or actual delivery date of the order'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='issue_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the PO was issued to the vendor'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateField(help_text='Date when the order was placed'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(default='pending', help_text='Current status of the PO (e.g., pending, completed, canceled)', max_length=100),
        ),
    ]
